### ISSUE TITLE
Keep history and credits

### ISSUE THREAD

**Issue by merwok** [wimglenn/pytest-freezer#5]
Hello and thanks for creating this fork!

Would you mind adding the original history to this repo?  I always find it useful to understand why some code is written the way it is.

Second, I don’t think it’s correct to remove the original author from all metadata.

Thanks!

**Comment by wimglenn** [comment]
Hi @merwok, it is [not actually a fork](https://github.com/ktosiek/pytest-freezegun/issues/19#issuecomment-1281829608), which is why the history is not there. Rewrote the code, the tests, the README, the packaging and the CI from scratch.

Of course the fixture name was kept the same to avoid unnecessary churn for users switching their requirements. There is acknowledgement in the [landing page](https://github.com/pytest-dev/pytest-freezer#acknowledgements) and it should remain easy to browse the history there.

**Comment by merwok** [comment]
Thanks for clarifying!  The README is clear indeed.  My bad!
